<?php
namespace JNi\TicketingBundle\Repository;
/**
 * AdmissionRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionRateRepository extends \Doctrine\ORM\EntityRepository
{
	public function getListByAgeDESC($type = "standard")
	{
		$queryBuilder = $this->createQueryBuilder('admissionRate');
		$queryBuilder
			->where('admissionRate.rateType = :type')
				->setParameter('type', $type)
			->orderBy('admissionRate.minimumAge', 'DESC');
		return $queryBuilder->getQuery()->getResult();
	}
}