<?php

namespace JNi\TicketingBundle\Repository;

/**
 * AdmissionRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionRateRepository extends \Doctrine\ORM\EntityRepository
{
	public function getListAdmissionRatesByRateDESC()
	{
		$queryBuilder = $this->createQueryBuilder('admissionRate');
		$queryBuilder->orderBy('admissionRate.rate', 'DESC');
		return $queryBuilder->getQuery()->getResult();
	}

	public function getListAdmissionRatesByAgeDESC()
	{
		$queryBuilder = $this->createQueryBuilder('admissionRate');
		$queryBuilder->orderBy('admissionRate.minimumAge', 'DESC');
		return $queryBuilder->getQuery()->getResult();
	}
}
