<?php

namespace JNi\TicketingBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
	// maximum date in future where invoice is registered
	public function getMaxDate()
	{
		$stringDate = $this->createQueryBuilder('i')
			->select('MAX(i.date)')
			->getQuery()
			->getSingleScalarResult();
		return new \DateTimeImmutable($stringDate);
	}
}
