<?php

namespace JNi\TicketingBundle\Repository;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{
	public function countForDay($day)
	{
		return (int) $this->createQueryBuilder('v')
			->leftJoin('v.invoice', 'i')
			->where('i.date = :day')
				->setParameter('day', $day)
			->select('count(v)')
			->getQuery()
			->getSingleScalarResult();
	}
}
