jni_ticketing_order_confirmation:
    path: /transaction/success/{key}
    defaults: { _controller: JNiTicketingBundle:Booking:confirmation }

jni_ticketing_home:
    path:     /
    defaults: { _controller: JNiTicketingBundle:Booking:index }

jni_ticketing_payment:
    path:     /payment
    defaults: { _controller: JNiTicketingBundle:Booking:payment }