services:
    ticketing.amount_calculator:
        class: JNi\TicketingBundle\Service\AmountCalculator
        arguments:
          - "@=service('doctrine.orm.entity_manager').getRepository('JNiTicketingBundle:AdmissionRate')"
        public: true
#
    ticketing.email:
        class: JNi\TicketingBundle\Service\EmailService
        arguments:
          - "@mailer"
          - "@templating"
        scope: request
        public: true
#
    ticketing.payment:
        class: JNi\TicketingBundle\Service\PaymentService
        arguments:
          - "%stripe_secret_key%"
        public: true
#
    ticketing.validator.not_busy_day:
        class: JNi\TicketingBundle\Validator\NotBusyDayValidator
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%ticketing_visitor_limit%"
        public: true
        tags:
          - { name: validator.constraint_validator, alias: ticketing.not_busy_day }
#
    ticketing.calendar:
        class: JNi\TicketingBundle\Service\BookingCalendar
        arguments:
          - "@=service('doctrine.orm.entity_manager').getRepository('JNiTicketingBundle:Invoice')"
          - "@=service('doctrine.orm.entity_manager').getRepository('JNiTicketingBundle:Visitor')"
          - "%ticketing_visitor_limit%"
        public: true